modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/tdbgo/Hangul/issues"

[[mods]]
modId="hangul"
version="${version}"
displayName="Hangul"
authors="PLAYCITY"
displayURL="https://modrinth.com/mod/hangul"
iconFile="assets/hangul/icon.png"
description='''Native Korean input and Korean-aware item, recipe, and command search.'''

[[mixins]]
config="hangul.client.mixins.json"

[[dependencies.hangul]]
modId="neoforge"
type="required"
versionRange="[26.1.0.19-beta],[26.1.1.15-beta],[26.1.2.104],[26.2.0.77]"
side="CLIENT"

[[dependencies.hangul]]
modId="minecraft"
type="required"
versionRange="[26.1],[26.1.1],[26.1.2],[26.2]"
side="CLIENT"
